### PR TITLE
implement thumbnails in java

### PR DESCRIPTION
**Pull request by kevodwyer**

### CODE REVIEW

**Comment by kevodwyer** [comment]
Can you test with FUSE to confirm? not possible on my machine.

**Comment by ianopolous** [comment]
You can test with the uploader class.

**Comment by ianopolous** [comment]
It would be great if we could move the java impl to the server package and make it implement an interface, then we wouldn't need to dummy gwt implementations.

**Comment by ianopolous** [comment]
Would also be good to have a test that generated a thumbnail in java, maybe for the logo or something that is already in git.

**Pull request merged**
