### PR TITLE
Reduce S3 auth read bandwidth

### PR DESCRIPTION
**Pull request by ianopolous**
This is done by only requesting the first 100 bytes of raw blocks, which is all that is needed.
All raw blocks are 8KiB - 1MiB+100 bytes

This should reduce inbound bandwidth to S3 by at least 80X, and up to 10,000X

### CODE REVIEW

**Comment by jonaswre** [comment]
```
[=============       ]  Read timed out retrieving api/v0/blockstore/auth-reads
[====================]  Read timed out retrieving api/v0/blockstore/auth-reads
[==                  ]  Read timed out retrieving api/v0/blockstore/auth-reads
```
Does this have something todo with the error im getting?

**Comment by ianopolous** [comment]
@jonaswre Quite possibly. S3 is very quick to rate limit us. Would be useful to know what kind of things you're doing to hit this, and we might be able to optimise further.

**Comment by jonaswre** [comment]
Im still trying to upload large files... I've uploaded 60 GBs so far but 240GB couldn't be uploaded... Files are between 200MB and 5-6 GB

**Review by kevodwyer — APPROVED** [review]

**Comment by jonaswre** [comment]
After a few hours of copying I got this error. 

java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 502 for URL: https://peergos.net/peergos/v0/mutable/getPointer?owner={owner}&writer={writer}
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 502 for URL: https://peergos.net/peergos/v0/mutable/getPointer?owner={owner}&writer={writer}
        at peergos.server.util.JavaPoster.lambda$publicGet$0(JavaPoster.java:179)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        ... 6 more
Caused by: java.io.IOException: Server returned HTTP response code: 502 for URL: https://peergos.net/peergos/v0/mutable/getPointer?owner={owner}&writer={writer}
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2048)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2043)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2042)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1609)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at peergos.server.util.JavaPoster.lambda$publicGet$0(JavaPoster.java:174)
        ... 7 more
Caused by: java.io.IOException: Server returned HTTP response code: 502 for URL: https://peergos.net/peergos/v0/mutable/getPointer?owner={owner}&writer={writer}
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3221)
        at java.base/java.net.URLConnection.getContentEncoding(URLConnection.java:531)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentEncoding(HttpsURLConnectionImpl.java:380)
        at peergos.server.util.JavaPoster.lambda$publicGet$0(JavaPoster.java:172)
        ... 7 more

**Comment by ianopolous** [comment]
@jonaswre We've deployed this PR now - would you be able to try again? Is this using the shell put command? With the skip arg?

**Comment by jonaswre** [comment]
Yes I can try again and this issue exists with or without skip

**Comment by ianopolous** [comment]
I've tested a similar bulk upload via shell put just now and can confirm the S3 bandwidth is 150x smaller.

**Comment by jonaswre** [comment]
Can you provide a new jar, so I can try it?

**Comment by jonaswre** [comment]
Thats a pretty huge improvement!

**Comment by ianopolous** [comment]
Yeah! The server looks idle now when "under load"! :-) (The reduction in bandwidth was purely server side between S3 and the server during auth read calls.)

**Comment by jonaswre** [comment]
But I still have the Read time outs 

```
|       [======              ]  Read timed out retrieving api/v0/blockstore/auth-reads
\       [================    ]  Read timed out retrieving api/v0/blockstore/auth-reads
|       [====                ]  Read timed out retrieving api/v0/blockstore/auth-reads
```

I'll let it upload and see if I get the Status code 502 again

**Comment by ianopolous** [comment]
It be retrying in that situation, so hopefully it succeeds anyway.

**Comment by jonaswre** [comment]
```
java.util.concurrent.CompletionException: java.net.SocketTimeoutException: Read timed out
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:674)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
        at peergos.shared.mutable.HttpMutablePointers.setPointer(HttpMutablePointers.java:71)
        at peergos.shared.mutable.HttpMutablePointers.setPointer(HttpMutablePointers.java:52)
        at peergos.shared.mutable.CachingPointers.setPointer(CachingPointers.java:43)
        at peergos.shared.mutable.BufferedPointers.lambda$commit$4(BufferedPointers.java:102)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at peergos.shared.mutable.BufferedPointers.commit(BufferedPointers.java:103)
        at peergos.shared.BufferedNetworkAccess.lambda$commit$8(BufferedNetworkAccess.java:146)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.shared.BufferedNetworkAccess.lambda$commit$11(BufferedNetworkAccess.java:146)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/jdk.internal.reflect.GeneratedConstructorAccessor20.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2048)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2043)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2042)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1609)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at peergos.server.util.JavaPoster.post(JavaPoster.java:69)
        at peergos.server.util.JavaPoster.post(JavaPoster.java:44)
        at peergos.shared.user.HttpPoster.post(HttpPoster.java:11)
        at peergos.server.util.JavaPoster.postUnzip(JavaPoster.java:39)
        at peergos.shared.user.HttpPoster.postUnzip(HttpPoster.java:17)
        ... 28 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1460)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1064)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:791)
        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:726)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1688)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3221)
        at java.base/java.net.URLConnection.getContentEncoding(URLConnection.java:531)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentEncoding(HttpsURLConnectionImpl.java:380)
        at peergos.server.util.JavaPoster.post(JavaPoster.java:67)
        ... 32 more
java.util.concurrent.CompletionException: java.net.SocketTimeoutException: Read timed out
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:674)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
        at peergos.shared.mutable.HttpMutablePointers.setPointer(HttpMutablePointers.java:71)
        at peergos.shared.mutable.HttpMutablePointers.setPointer(HttpMutablePointers.java:52)
        at peergos.shared.mutable.CachingPointers.setPointer(CachingPointers.java:43)
        at peergos.shared.mutable.BufferedPointers.lambda$commit$4(BufferedPointers.java:102)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at peergos.shared.mutable.BufferedPointers.commit(BufferedPointers.java:103)
        at peergos.shared.BufferedNetworkAccess.lambda$commit$8(BufferedNetworkAccess.java:146)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.shared.BufferedNetworkAccess.lambda$commit$11(BufferedNetworkAccess.java:146)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/jdk.internal.reflect.GeneratedConstructorAccessor20.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2048)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2043)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2042)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1609)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at peergos.server.util.JavaPoster.post(JavaPoster.java:69)
        at peergos.server.util.JavaPoster.post(JavaPoster.java:44)
        at peergos.shared.user.HttpPoster.post(HttpPoster.java:11)
        at peergos.server.util.JavaPoster.postUnzip(JavaPoster.java:39)
        at peergos.shared.user.HttpPoster.postUnzip(HttpPoster.java:17)
        ... 28 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1460)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1064)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:791)
        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:726)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1688)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3221)
        at java.base/java.net.URLConnection.getContentEncoding(URLConnection.java:531)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentEncoding(HttpsURLConnectionImpl.java:380)
        at peergos.server.util.JavaPoster.post(JavaPoster.java:67)
        ... 32 more
```

I guess no success

**Comment by ianopolous** [comment]
The mutable pointers don't have a retry (we haven't hit this before), but I can add a retry backoff.

**Comment by jonaswre** [comment]
Could you also add a information to the cli, so that I can see the file that's failing? And maybe get information about how many files were transmitted and how many are missing.

**Comment by ianopolous** [comment]
Yep, I'll expand the feedback too.

**Comment by ianopolous** [comment]
That's all in PR here: https://github.com/Peergos/Peergos/pull/960

**Pull request merged**
