### PR TITLE
Use a retrying mutable pointers

### PR DESCRIPTION
**Pull request by ianopolous**
Also make shell progress bars show path and filename, 1 per line, with file count progress, and semi-aligned bars. e.g.
```
(1/44) images/favicon.png                          /	[====================]	
(2/44) images/security-champion.jpg                /	[====================]	
(3/44) images/GavinBelsin.jpg                      /	[====================]	
(4/44) images/penrose-nobel.webp                   /	[====================]	
(5/44) images/dl-dog1.jpg                          /	[====================]
```

### CODE REVIEW

**Review by kevodwyer — APPROVED** [review]

**Comment by jonaswre** [comment]
@ianopolous is this already deployed?

**Comment by ianopolous** [comment]
These are all client side changes. So you'll need a new jar. Either run "ant dist" in the web-ui repo. Or I've put the latest here: https://peergos.net/#%7B%22secretLink%22:true%2c%22link%22:%22#6MDZhRRPT4ugkJuUfcWtaZodN5QYzkZKJtHpDHomFJrVhNSZysiFYimpgtcA2F/6MDZhRRPT4ugkJuUfcRzRbPpFimcBNJx2N9TJDnL4W3ETYhwdsWdvgCkXkwipF/2msZ72SumWPWPMBebu2gWy4yrkE47gWRD6QE5x3eStJfG2vLeAVZDJ1XDqJ1XfQZiiu92P9JjdRF8jzybEQgF7WXj4MoR1P/5Pf7Svd8dBLgnfjHYRLq5nmRzPzZphTeEyjLZsizLWtiWCCVjFq%22%7D

**Comment by jonaswre** [comment]
I'll just take your jar. But just for my understanding is the cli also in the web-ui repo?

**Comment by jonaswre** [comment]
I must say being able to see the files that were uploaded is great!

To now got this error. And maybe its just a coincident but the filename has a ,

java.util.concurrent.CompletionException: java.lang.RuntimeException: ERROR%3A+integer+out+of+range
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:674)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
        at peergos.shared.storage.ContentAddressedStorage$HTTP.authWrites(ContentAddressedStorage.java:343)
        at peergos.shared.storage.DirectS3BlockStore.bulkPutRaw(DirectS3BlockStore.java:171)
        at peergos.shared.storage.DirectS3BlockStore.lambda$putRaw$6(DirectS3BlockStore.java:148)
        at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
        at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
        at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
        at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
        at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at peergos.shared.storage.DirectS3BlockStore.lambda$putRaw$9(DirectS3BlockStore.java:155)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.shared.storage.DirectS3BlockStore.putRaw(DirectS3BlockStore.java:139)
        at peergos.shared.storage.RetryStorage.lambda$putRaw$9(RetryStorage.java:112)
        at peergos.shared.storage.RetryStorage.recurse(RetryStorage.java:51)
        at peergos.shared.storage.RetryStorage.lambda$recurse$1(RetryStorage.java:61)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: ERROR%3A+integer+out+of+range
        at peergos.server.util.JavaPoster.post(JavaPoster.java:80)
        at peergos.server.util.JavaPoster.post(JavaPoster.java:44)
        at peergos.shared.user.HttpPoster.post(HttpPoster.java:11)
        at peergos.server.util.JavaPoster.postUnzip(JavaPoster.java:39)
        at peergos.shared.user.HttpPoster.postUnzip(HttpPoster.java:17)
        at peergos.shared.storage.ContentAddressedStorage$HTTP.authWrites(ContentAddressedStorage.java:339)
        ... 28 more
java.util.concurrent.CompletionException: java.lang.RuntimeException: ERROR%3A+integer+out+of+range
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:674)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
        at peergos.shared.storage.ContentAddressedStorage$HTTP.authWrites(ContentAddressedStorage.java:343)
        at peergos.shared.storage.DirectS3BlockStore.bulkPutRaw(DirectS3BlockStore.java:171)
        at peergos.shared.storage.DirectS3BlockStore.lambda$putRaw$6(DirectS3BlockStore.java:148)
        at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
        at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
        at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
        at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
        at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at peergos.shared.storage.DirectS3BlockStore.lambda$putRaw$9(DirectS3BlockStore.java:155)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
        at peergos.shared.storage.DirectS3BlockStore.putRaw(DirectS3BlockStore.java:139)
        at peergos.shared.storage.RetryStorage.lambda$putRaw$9(RetryStorage.java:112)
        at peergos.shared.storage.RetryStorage.recurse(RetryStorage.java:51)
        at peergos.shared.storage.RetryStorage.lambda$recurse$1(RetryStorage.java:61)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: ERROR%3A+integer+out+of+range
        at peergos.server.util.JavaPoster.post(JavaPoster.java:80)
        at peergos.server.util.JavaPoster.post(JavaPoster.java:44)
        at peergos.shared.user.HttpPoster.post(HttpPoster.java:11)
        at peergos.server.util.JavaPoster.postUnzip(JavaPoster.java:39)
        at peergos.shared.user.HttpPoster.postUnzip(HttpPoster.java:17)
        at peergos.shared.storage.ContentAddressedStorage$HTTP.authWrites(ContentAddressedStorage.java:339)
        ... 28 more

**Comment by jonaswre** [comment]
Upload from the UI results in the same error when just uploading that file

**Comment by ianopolous** [comment]
Hmm that error is postgres complaining that the integer for the size of pending (unconfirmed) writes is too big. The integer type in postgres is 32bit, so 4 GiB. That suggests the space usage recalculation on the server is lagging behind. It will likely resolve itself once the server catches up, so probably trying again tomorrow will work. We can also speed up the usage calculator which is not parallelised at all. I will also look into changing that integer size in postgres.

**Comment by jonaswre** [comment]
The upload worked now. But peergos properties reports more files then windows explorer. Which i'll need to find fiqure out.

**Pull request merged**
