### PR TITLE
add java 11 support via gwt 2.8.3 custom build

### PR DESCRIPTION
**Pull request by kevodwyer**
see BUILD-GWT.txt in gwt folder for instructions on how to build

### CODE REVIEW

**Comment by cboddy** [comment]
> Files changed 6,939
o_0

**Comment by ianopolous** [comment]
I've tested a bunch of stuff. LGTM! The only problem now is the directories in the jar have acquired a timestamp, which breaks reproducible builds.

**Comment by ianopolous** [comment]
That problem with dir timestamps seems to have happened earlier. So this is good to go.

**Comment by ianopolous** [comment]
Just need to figure out why test classpath is broken in java 11 before merging this.

**Comment by ianopolous** [comment]
hmm java thinks the output jar from this is invalid for some reason, but it opens fine as a zip

**Pull request merged**
